language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - chmod +x ./tests/travis/laravel-installer.sh
  - ./tests/travis/laravel-installer.sh

script: phpunit --coverage-text --debug